apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: cnv
  name: 00-configure-net-and-storage
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - enabled: true
          name: openvswitch.service
        - contents: |
            [Unit]
            After=network-online.target
            Wants=network-online.target
            After=openvswitch.service
            [Service]
            Type=oneshot
            ExecStart=/bin/sh /var/setup-ovs.sh
            [Install]
            WantedBy=multi-user.target
          name: setup-ovs.service
          enabled: true
        - contents: |
            [Unit]
            Description=create datastore mount
            [Service]
            Type=oneshot
            ExecStart=/bin/mkdir -p /var/mnt/datastore
            [Install]
            WantedBy=multi-user.target
          name: create-datastore.service
          enabled: true
        - contents: |
            [Unit]
            Description=Set SELinux chcon for hostpath-provisioner
            Before=kubelet.service
            After=var-mnt-datastore.mount
            [Service]
            ExecStart=/usr/bin/chcon -Rt container_file_t /var/mnt/datastore
            [Install]
            WantedBy=multi-user.target
          name: selinux-hostpath.service
          enabled: true
        - contents: |
            [Unit]
            Description=datastore mount
            After=create-datastore.service
            [Mount]
            What=/dev/sda5
            Where=/var/mnt/datastore
            Type=xfs
            Options=defaults
            [Install]
            WantedBy=multi-user.target
          name: var-mnt-datastore.mount
          enabled: true
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2V0IC1leAoKaWYgW1sgJChubWNsaSBjb25uIHwgZ3JlcCAtYyBvdnMpIC1lcSAwIF1dOyB0aGVuCiAgZWNobyAiY29uZmlndXJlIG92cyBib25kaW5nIgogIHByaW1hcnlfbWFjPSQoY2F0IC9ib290L21hY19hZGRyZXNzZXMgfCBhd2sgLUY9ICcvUFJJTUFSWV9NQUMvIHtwcmludCAkMn0nKQogIHNlY29uZGFyeV9tYWM9JChjYXQgL2Jvb3QvbWFjX2FkZHJlc3NlcyB8IGF3ayAtRj0gJy9TRUNPTkRBUllfTUFDLyB7cHJpbnQgJDJ9JykKICAKICBkZWZhdWx0X2RldmljZT0iIgogIHNlY29uZGFyeV9kZXZpY2U9IiIKICBwcm9maWxlX25hbWU9IiIKICBzZWNvbmRhcnlfcHJvZmlsZV9uYW1lPSIiCiAgCiAgCiAgZm9yIGRldiBpbiAkKG5tY2xpIGRldmljZSBzdGF0dXMgfCBhd2sgJy9ldGhlcm5ldC8ge3ByaW50ICQxfScpOyBkbwogICAgZGV2X21hYz0kKG5tY2xpIC1nIEdFTkVSQUwuSFdBRERSIGRldiBzaG93ICRkZXYgfCBzZWQgLWUgJ3MvXFwvL2cnIHwgdHIgJ1tBLVpdJyAnW2Etel0nKQogICAgY2FzZSAkZGV2X21hYyBpbgogICAgICAkcHJpbWFyeV9tYWMpCiAgICAgICAgZGVmYXVsdF9kZXZpY2U9JGRldgogICAgICAgIHByb2ZpbGVfbmFtZT0kKG5tY2xpIC1nIEdFTkVSQUwuQ09OTkVDVElPTiBkZXYgc2hvdyAkZGV2KQogICAgICAgIDs7CiAgICAgICRzZWNvbmRhcnlfbWFjKQogICAgICAgIHNlY29uZGFyeV9kZXZpY2U9JGRldgogICAgICAgIHNlY29uZGFyeV9wcm9maWxlX25hbWU9JChubWNsaSAtZyBHRU5FUkFMLkNPTk5FQ1RJT04gZGV2IHNob3cgJGRldikKICAgICAgICA7OwogICAgICAqKQogICAgICAgIDs7CiAgICAgZXNhYwogIGRvbmUKICBlY2hvIC1lICJkZWZhdWx0IGRldjogJGRlZmF1bHRfZGV2aWNlICgkcHJvZmlsZV9uYW1lKVxuc2Vjb25kYXJ5IGRldjogJHNlY29uZGFyeV9kZXZpY2UgKCRzZWNvbmRhcnlfcHJvZmlsZV9uYW1lKSIKICAKICBtYWM9JChzdWRvIG5tY2xpIC1nIEdFTkVSQUwuSFdBRERSIGRldiBzaG93ICRkZWZhdWx0X2RldmljZSB8IHNlZCAtZSAncy9cXC8vZycpCiAgCiAgIyBtYWtlIGJyaWRnZQogICNubWNsaSBjb25uIGFkZCB0eXBlIG92cy1icmlkZ2UgY29ubi5pbnRlcmZhY2UgYnJjbnYgaXB2NC5kaGNwLWNsaWVudC1pZCAwMTokbWFjCiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtYnJpZGdlIGNvbm4uaW50ZXJmYWNlIGJyY252CiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtcG9ydCBjb25uLmludGVyZmFjZSBwb3J0MCBtYXN0ZXIgYnJjbnYKICBubWNsaSBjb25uIGFkZCB0eXBlIG92cy1wb3J0IGNvbm4uaW50ZXJmYWNlIGJyY252LXBvcnQgbWFzdGVyIGJyY252CiMgIG5tY2xpIGNvbm4gYWRkIHR5cGUgb3ZzLWludGVyZmFjZSBjb25uLmlkIGJyY252LWlmYWNlIGNvbm4uaW50ZXJmYWNlIGJyY252IG1hc3RlciBicmNudi1wb3J0IGlwdjQubWV0aG9kIGF1dG8gY29ubmVjdGlvbi5hdXRvY29ubmVjdCBubyBpcHY0LmRoY3AtY2xpZW50LWlkIDAxOiRtYWMKICBubWNsaSBjb25uIGFkZCB0eXBlIG92cy1pbnRlcmZhY2UgY29ubi5pZCBicmNudi1pZmFjZSBjb25uLmludGVyZmFjZSBicmNudiBtYXN0ZXIgYnJjbnYtcG9ydCBpcHY0Lm1ldGhvZCBhdXRvIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3Qgbm8gaXB2NC5kaGNwLWNsaWVudC1pZCAwMTokbWFjIDgwMi0zLWV0aGVybmV0LmNsb25lZC1tYWMtYWRkcmVzcyAkbWFjCgogICMgbWFrZSBib25kCiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtcG9ydCBjb25uLmludGVyZmFjZSBib25kMCBtYXN0ZXIgYnJjbnYgb3ZzLXBvcnQuYm9uZC1tb2RlIGJhbGFuY2Utc2xiCiAgbm1jbGkgY29ubiBhZGQgdHlwZSBldGhlcm5ldCBjb25uLmludGVyZmFjZSAkZGVmYXVsdF9kZXZpY2UgbWFzdGVyIGJvbmQwCiAgbm1jbGkgY29ubiBhZGQgdHlwZSBldGhlcm5ldCBjb25uLmludGVyZmFjZSAkc2Vjb25kYXJ5X2RldmljZSBtYXN0ZXIgYm9uZDAKICBubWNsaSBjb25uIGRvd24gIiRwcm9maWxlX25hbWUiIHx8IHRydWUKICBubWNsaSBjb25uIG1vZCAiJHByb2ZpbGVfbmFtZSIgY29ubmVjdGlvbi5hdXRvY29ubmVjdCBubyB8fCB0cnVlCiAgbm1jbGkgY29ubiBkb3duICIkc2Vjb25kYXJ5X3Byb2ZpbGVfbmFtZSIgfHwgdHJ1ZQogIG5tY2xpIGNvbm4gbW9kICIkc2Vjb25kYXJ5X3Byb2ZpbGVfbmFtZSIgY29ubmVjdGlvbi5hdXRvY29ubmVjdCBubyB8fCB0cnVlCiAgaWYgISBubWNsaSBjb25uIHVwIGJyY252LWlmYWNlOyB0aGVuCiAgICAgIG5tY2xpIGNvbm4gdXAgIiRwcm9maWxlX25hbWUiIHx8IHRydWUKICAgICAgbm1jbGkgY29ubiBtb2QgIiRwcm9maWxlX25hbWUiIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3QgeWVzCiAgICAgIG5tY2xpIGNvbm4gdXAgIiRzZWNvbmRhcnlfcHJvZmlsZV9uYW1lIiB8fCB0cnVlCiAgICAgIG5tY2xpIGNvbm4gbW9kICIkc2Vjb25kYXJ5X3Byb2ZpbGVfbmFtZSIgY29ubmVjdGlvbi5hdXRvY29ubmVjdCB5ZXMKICAgICAgbm1jbGkgYyBkZWxldGUgJChubWNsaSBjIHNob3cgfGdyZXAgb3ZzLWNudiB8YXdrICd7cHJpbnQgJDF9JykgfHwgdHJ1ZQogIGVsc2UKICAgICAgbm1jbGkgY29ubiBtb2QgYnJjbnYtaWZhY2UgY29ubmVjdGlvbi5hdXRvY29ubmVjdCB5ZXMKICAgICAgcmVib290CiAgZmkKZWxzZQogICAgZWNobyAib3ZzIGJyaWRnZSBhbHJlYWR5IHByZXNlbnQiCmZpCg==
          filesystem: root
          mode: 484
          path: /var/setup-ovs.sh
