apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: cnv
  name: 00-configure-net-and-storage
spec:
  config:
    ignition:
      version: 2.2.0
    systemd:
      units:
        - enabled: true
          name: openvswitch.service
        - contents: |
            [Unit]
            After=NetworkManager-wait-online.service
            After=openvswitch.service
            [Service]
            Type=oneshot
            ExecStart=/bin/sh /var/setup-ovs.sh
            [Install]
            WantedBy=multi-user.target
          name: setup-ovs.service
          enabled: true
        - contents: |
            [Unit]
            Description=create datastore mount
            [Service]
            Type=oneshot
            ExecStart=/bin/mkdir -p /var/mnt/datastore
            [Install]
            WantedBy=multi-user.target
          name: create-datastore.service
          enabled: true
        - contents: |
            [Unit]
            Description=Set SELinux chcon for hostpath-provisioner
            Before=kubelet.service
            After=var-mnt-datastore.mount
            [Service]
            ExecStart=/usr/bin/chcon -Rt container_file_t /var/mnt/datastore
            [Install]
            WantedBy=multi-user.target
          name: selinux-hostpath.service
          enabled: true
        - contents: |
            [Unit]
            Description=datastore mount
            After=create-datastore.service
            [Mount]
            What=/dev/sda5
            Where=/var/mnt/datastore
            Type=xfs
            Options=defaults
            [Install]
            WantedBy=multi-user.target
          name: var-mnt-datastore.mount
          enabled: true
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,IyEvdXNyL2Jpbi9lbnYgYmFzaAoKc2V0IC1leAoKaWYgW1sgJChubWNsaSBjb25uIHwgZ3JlcCAtYyBvdnMpIC1lcSAwIF1dOyB0aGVuCiAgZWNobyAiY29uZmlndXJlIG92cyBib25kaW5nIgogIHByaW1hcnlfbWFjPSQoY2F0IC9ib290L21hY19hZGRyZXNzZXMgfCBhd2sgLUY9ICcvUFJJTUFSWV9NQUMvIHtwcmludCAkMn0nKQogIHNlY29uZGFyeV9tYWM9JChjYXQgL2Jvb3QvbWFjX2FkZHJlc3NlcyB8IGF3ayAtRj0gJy9TRUNPTkRBUllfTUFDLyB7cHJpbnQgJDJ9JykKICAKICBkZWZhdWx0X2RldmljZT0iIgogIHNlY29uZGFyeV9kZXZpY2U9IiIKICBwcm9maWxlX25hbWU9IiIKICBzZWNvbmRhcnlfcHJvZmlsZV9uYW1lPSIiCiAgCiAgCiAgZm9yIGRldiBpbiAkKG5tY2xpIGRldmljZSBzdGF0dXMgfCBhd2sgJy9ldGhlcm5ldC8ge3ByaW50ICQxfScpOyBkbwogICAgZGV2X21hYz0kKG5tY2xpIC1nIEdFTkVSQUwuSFdBRERSIGRldiBzaG93ICRkZXYgfCBzZWQgLWUgJ3MvXFwvL2cnIHwgdHIgJ1tBLVpdJyAnW2Etel0nKQogICAgY2FzZSAkZGV2X21hYyBpbgogICAgICAkcHJpbWFyeV9tYWMpCiAgICAgICAgZGVmYXVsdF9kZXZpY2U9JGRldgogICAgICAgIHByb2ZpbGVfbmFtZT0kKG5tY2xpIC1nIEdFTkVSQUwuQ09OTkVDVElPTiBkZXYgc2hvdyAkZGV2KQogICAgICAgIDs7CiAgICAgICRzZWNvbmRhcnlfbWFjKQogICAgICAgIHNlY29uZGFyeV9kZXZpY2U9JGRldgogICAgICAgIHNlY29uZGFyeV9wcm9maWxlX25hbWU9JChubWNsaSAtZyBHRU5FUkFMLkNPTk5FQ1RJT04gZGV2IHNob3cgJGRldikKICAgICAgICA7OwogICAgICAqKQogICAgICAgIDs7CiAgICAgZXNhYwogIGRvbmUKICBlY2hvIC1lICJkZWZhdWx0IGRldjogJGRlZmF1bHRfZGV2aWNlICgkcHJvZmlsZV9uYW1lKVxuc2Vjb25kYXJ5IGRldjogJHNlY29uZGFyeV9kZXZpY2UgKCRzZWNvbmRhcnlfcHJvZmlsZV9uYW1lKSIKICAKICBtYWM9JChzdWRvIG5tY2xpIC1nIEdFTkVSQUwuSFdBRERSIGRldiBzaG93ICRkZWZhdWx0X2RldmljZSB8IHNlZCAtZSAncy9cXC8vZycpCiAgCiAgIyBtYWtlIGJyaWRnZQogICNubWNsaSBjb25uIGFkZCB0eXBlIG92cy1icmlkZ2UgY29ubi5pbnRlcmZhY2UgYnJjbnYgaXB2NC5kaGNwLWNsaWVudC1pZCAwMTokbWFjCiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtYnJpZGdlIGNvbm4uaW50ZXJmYWNlIGJyY252CiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtcG9ydCBjb25uLmludGVyZmFjZSBwb3J0MCBtYXN0ZXIgYnJjbnYKICBubWNsaSBjb25uIGFkZCB0eXBlIG92cy1wb3J0IGNvbm4uaW50ZXJmYWNlIGJyY252LXBvcnQgbWFzdGVyIGJyY252CiAgbm1jbGkgY29ubiBhZGQgdHlwZSBvdnMtaW50ZXJmYWNlIGNvbm4uaWQgYnJjbnYtaWZhY2UgY29ubi5pbnRlcmZhY2UgYnJjbnYgbWFzdGVyIGJyY252LXBvcnQgaXB2NC5tZXRob2QgYXV0byBjb25uZWN0aW9uLmF1dG9jb25uZWN0IG5vIGlwdjQuZGhjcC1jbGllbnQtaWQgMDE6JG1hYwoKICAjIG1ha2UgYm9uZAogIG5tY2xpIGNvbm4gYWRkIHR5cGUgb3ZzLXBvcnQgY29ubi5pbnRlcmZhY2UgYm9uZDAgbWFzdGVyIGJyY252IG92cy1wb3J0LmJvbmQtbW9kZSBiYWxhbmNlLXNsYgogIG5tY2xpIGNvbm4gYWRkIHR5cGUgZXRoZXJuZXQgY29ubi5pbnRlcmZhY2UgJGRlZmF1bHRfZGV2aWNlIG1hc3RlciBib25kMAogIG5tY2xpIGNvbm4gYWRkIHR5cGUgZXRoZXJuZXQgY29ubi5pbnRlcmZhY2UgJHNlY29uZGFyeV9kZXZpY2UgbWFzdGVyIGJvbmQwCiAgbm1jbGkgY29ubiBkb3duICIkcHJvZmlsZV9uYW1lIiB8fCB0cnVlCiAgbm1jbGkgY29ubiBtb2QgIiRwcm9maWxlX25hbWUiIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3Qgbm8gfHwgdHJ1ZQogIG5tY2xpIGNvbm4gZG93biAiJHNlY29uZGFyeV9wcm9maWxlX25hbWUiIHx8IHRydWUKICBubWNsaSBjb25uIG1vZCAiJHNlY29uZGFyeV9wcm9maWxlX25hbWUiIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3Qgbm8gfHwgdHJ1ZQogIGlmICEgbm1jbGkgY29ubiB1cCBicmNudi1pZmFjZTsgdGhlbgogICAgICBubWNsaSBjb25uIHVwICIkcHJvZmlsZV9uYW1lIiB8fCB0cnVlCiAgICAgIG5tY2xpIGNvbm4gbW9kICIkcHJvZmlsZV9uYW1lIiBjb25uZWN0aW9uLmF1dG9jb25uZWN0IHllcwogICAgICBubWNsaSBjb25uIHVwICIkc2Vjb25kYXJ5X3Byb2ZpbGVfbmFtZSIgfHwgdHJ1ZQogICAgICBubWNsaSBjb25uIG1vZCAiJHNlY29uZGFyeV9wcm9maWxlX25hbWUiIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3QgeWVzCiAgICAgIG5tY2xpIGMgZGVsZXRlICQobm1jbGkgYyBzaG93IHxncmVwIG92cy1jbnYgfGF3ayAne3ByaW50ICQxfScpIHx8IHRydWUKICBlbHNlCiAgICAgIG5tY2xpIGNvbm4gbW9kIGJyY252LWlmYWNlIGNvbm5lY3Rpb24uYXV0b2Nvbm5lY3QgeWVzCiAgICAgIHJlYm9vdAogIGZpCmVsc2UKICAgIGVjaG8gIm92cyBicmlkZ2UgYWxyZWFkeSBwcmVzZW50IgpmaQo=
          filesystem: root
          mode: 484
          path: /var/setup-ovs.sh
